language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
# command to run tests
script:
  - python manage.py test
env:
  - DJANGO_VERSION=3.0.5