language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
# command to run tests
script:
  - pytest
env:
  - DJANGO_VERSION=3.0.5